FROM guoyk/common-jdk:8

ENV APOLLO_VERSION 1.3.0

RUN curl -sSLO https://mirrors.landzero.net/github.com/ctripcorp/apollo/releases/download/v${APOLLO_VERSION}/apollo-portal-1.3.0-github.zip && \
    curl -sSLO https://mirrors.landzero.net/github.com/ctripcorp/apollo/releases/download/v${APOLLO_VERSION}/apollo-configservice-1.3.0-github.zip && \
    curl -sSLO https://mirrors.landzero.net/github.com/ctripcorp/apollo/releases/download/v${APOLLO_VERSION}/apollo-adminservice-1.3.0-github.zip
